// db.assessments.createIndex({ customerId: 1 }, { background: true })
// db.assessments.createIndex({ externalTenantId: 1 }, { background: true })
// db.assessments.createIndex({ assessmentId: 1 }, { background: true })
// db.assessments.createIndex({ predictorMasterId: 1 }, { background: true })
// db.assessments.createIndex({ externalAssessmentId: 1 }, { background: true })
// db.assessments.createIndex({ externalApplicationId: 1 }, { background: true })
// db.assessments.createIndex({ externalApplicantId: 1 }, { background: true })
// db.assessments.createIndex({ candidateEmail: 1 }, { background: true })
// db.assessments.createIndex({ status: 1 }, { background: true })
// db.assessments.createIndex({ createdAt: 1 }, { background: true })
// db.assessments.createIndex({ customerId: 1, externalTenantId: 1, externalAssessmentId: 1 }, { background: true })
