export const FARGATE_EXPRESS_PORT = process.env.FARGATE_EXPRESS_PORT;
export const OFFLINE_DOCUMENTDB_PRIMARY_URI =
  process.env.OFFLINE_DOCUMENTDB_PRIMARY_URI;
export const OFFLINE_DOCUMENTDB_SECONDARY_URI =
  process.env.OFFLINE_DOCUMENTDB_SECONDARY_URI;
